name: Test
on:
  push:
  workflow_dispatch:
jobs:
  prerender:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up environment for Puppeteer
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 \
            libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
            libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
            libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
            libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release \
            xdg-utils wget
      
      - name: Install dependencies and build 🔧
        run: |
          npm install
          npm install react-snap
          npm run build

      - name: Add react-snap configuration
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          path: example/package.json
          data: |
            {
              "reactSnap": {
                "source": "dist",
                "puppeteerArgs": [
                  "--no-sandbox",
                  "--disable-setuid-sandbox",
                  "--disable-dev-shm-usage",
                  "--single-process"
                ]}
            }

      - name: Pre-render application
        run: |
          npx react-snap
          echo "Done!"

      - name: Verify SSR
        shell: bash
        run: |
          if grep -q 'Client says hello!' dist/index.html; then exit 0; else exit 1; fi

      # - name: Test
      #   uses: brycedorn/react-snap-action@v1.0
      #   with:
      #     source: example/dist
